#!/usr/bin/env python3
"""Generate the checked-in Rust operation manifest from OpenCode OpenAPI.

This is deliberately small. It validates the operation IDs used by the first
vertical slice without claiming that current Rust generators can correctly
translate every OpenAPI 3.1 union in the upstream contract.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec" / "openapi.json"
UPSTREAM = ROOT / "spec" / "upstream.json"
OUTPUT = ROOT / "src" / "generated" / "operations.rs"

OPERATIONS = [
    ("SESSION_LIST", "session.list"),
    ("SESSION_GET", "session.get"),
    ("SESSION_CREATE", "session.create"),
    ("SESSION_PROMPT", "session.prompt"),
    ("SESSION_ABORT", "session.abort"),
    ("EVENT_SUBSCRIBE", "event.subscribe"),
]


def operation_index(spec: dict) -> dict[str, tuple[str, str]]:
    found: dict[str, tuple[str, str]] = {}
    for path, path_item in spec.get("paths", {}).items():
        for method, operation in path_item.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete", "head", "options"}:
                continue
            if not isinstance(operation, dict):
                continue
            operation_id = operation.get("operationId")
            if operation_id:
                found[operation_id] = (method.upper(), path)
    return found


def render(spec: dict, upstream: dict) -> str:
    index = operation_index(spec)
    missing = [operation_id for _, operation_id in OPERATIONS if operation_id not in index]
    if missing:
        raise SystemExit(f"pinned OpenAPI contract is missing required operations: {', '.join(missing)}")

    lines = [
        "// @generated by scripts/generate_contract.py. Do not edit by hand.",
        f'pub const CONTRACT_UPSTREAM_SHA: &str = "{upstream["upstream_commit"]}";',
        "",
    ]
    for rust_name, operation_id in OPERATIONS:
        method, path = index[operation_id]
        lines.extend(
            [
                f'pub const {rust_name}_METHOD: &str = "{method}";',
                f'pub const {rust_name}_PATH: &str = "{path}";',
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not SPEC.exists():
        if args.check:
            print("spec/openapi.json is not checked in yet; contract refresh workflow will create it")
            return
        raise SystemExit("spec/openapi.json does not exist; run scripts/update-openapi first")

    spec = json.loads(SPEC.read_text())
    upstream = json.loads(UPSTREAM.read_text())
    output = render(spec, upstream)

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != output:
            raise SystemExit("generated contract manifest is stale; run scripts/generate_contract.py")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output)


if __name__ == "__main__":
    main()
