#!/usr/bin/env python3
"""Generate the checked-in Rust operation manifest from OpenCode OpenAPI.

The manifest validates all stable legacy/current operations plus the explicitly
supported V2 preview operations. Experimental/worktree/sync operation families
are excluded from "current complete" unless they have a stable operation ID
used by the official SDK (for example tool.*).
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec" / "openapi.json"
UPSTREAM = ROOT / "spec" / "upstream.json"
OUTPUT = ROOT / "src" / "generated" / "operations.rs"

V2_OPERATIONS = {
    "v2.session.list",
    "v2.session.get",
    "v2.session.create",
    "v2.session.prompt",
    "v2.session.wait",
    "v2.session.interrupt",
    "v2.session.events",
    "v2.event.subscribe",
    "v2.model.list",
    "v2.provider.list",
    "v2.provider.get",
    "v2.fs.read",
    "v2.fs.list",
    "v2.fs.find",
    "v2.permission.request.list",
    "v2.permission.saved.list",
    "v2.permission.saved.remove",
    "v2.question.request.list",
    "v2.session.active",
    "v2.session.switchAgent",
    "v2.session.switchModel",
    "v2.session.compact",
    "v2.session.context",
    "v2.session.history",
    "v2.session.message",
    "v2.session.messages",
    "v2.session.revert.stage",
    "v2.session.revert.clear",
    "v2.session.revert.commit",
    "v2.session.permission.list",
    "v2.session.permission.create",
    "v2.session.permission.get",
    "v2.session.permission.reply",
    "v2.session.question.list",
    "v2.session.question.reply",
    "v2.session.question.reject",
    "v2.health.get",
    "v2.location.get",
    "v2.agent.list",
    "v2.command.list",
    "v2.skill.list",
    "v2.reference.list",
    "v2.integration.list",
    "v2.integration.get",
    "v2.integration.connect.key",
    "v2.integration.connect.oauth",
    "v2.integration.attempt.status",
    "v2.integration.attempt.cancel",
    "v2.integration.attempt.complete",
    "v2.credential.update",
    "v2.credential.remove",
}

CURRENT_EXCLUDED_PREFIXES = (
    "v2.",
    "experimental.",
    "worktree.",
    "sync.",
)


def operation_index(spec: dict) -> dict[str, tuple[str, str]]:
    found: dict[str, tuple[str, str]] = {}
    for path, path_item in spec.get("paths", {}).items():
        for method, operation in path_item.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete", "head", "options"}:
                continue
            if not isinstance(operation, dict):
                continue
            operation_id = operation.get("operationId")
            if operation_id:
                found[operation_id] = (method.upper(), path)
    return found


def current_operations(index: dict[str, tuple[str, str]]) -> set[str]:
    return {
        operation_id
        for operation_id in index
        if not operation_id.startswith(CURRENT_EXCLUDED_PREFIXES)
    }


def rust_name(operation_id: str) -> str:
    return "OP_" + re.sub(r"[^A-Za-z0-9]+", "_", operation_id).upper()


def render(spec: dict, upstream: dict) -> str:
    index = operation_index(spec)
    required = current_operations(index) | V2_OPERATIONS
    missing = sorted(required - index.keys())
    if missing:
        raise SystemExit(
            f"pinned OpenAPI contract is missing required operations: {', '.join(missing)}"
        )

    lines = [
        "// @generated by scripts/generate_contract.py. Do not edit by hand.",
        f'pub const CONTRACT_UPSTREAM_SHA: &str = "{upstream["upstream_commit"]}";',
        "",
    ]
    for operation_id in sorted(required):
        method, path = index[operation_id]
        name = rust_name(operation_id)
        lines.extend(
            [
                f'pub const {name}_METHOD: &str = "{method}";',
                f'pub const {name}_PATH: &str = "{path}";',
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not SPEC.exists():
        if args.check:
            print("spec/openapi.json is not checked in yet; contract refresh workflow will create it")
            return
        raise SystemExit("spec/openapi.json does not exist; run scripts/update-openapi first")

    spec = json.loads(SPEC.read_text())
    upstream = json.loads(UPSTREAM.read_text())
    output = render(spec, upstream)

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != output:
            raise SystemExit("generated contract manifest is stale; run scripts/generate_contract.py")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output)


if __name__ == "__main__":
    main()
