#!/usr/bin/env python3
"""Generate the checked-in Rust operation manifest from OpenCode OpenAPI.

This is deliberately small. It validates the operation IDs used by the first
legacy/current and V2 vertical slices without claiming that current Rust
generators can correctly translate every OpenAPI 3.1 union in the upstream
contract.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec" / "openapi.json"
UPSTREAM = ROOT / "spec" / "upstream.json"
OUTPUT = ROOT / "src" / "generated" / "operations.rs"

OPERATIONS = [
    ("SESSION_LIST", "session.list"),
    ("SESSION_GET", "session.get"),
    ("SESSION_CREATE", "session.create"),
    ("SESSION_PROMPT", "session.prompt"),
    ("SESSION_ABORT", "session.abort"),
    ("EVENT_SUBSCRIBE", "event.subscribe"),
    ("V2_SESSION_LIST", "v2.session.list"),
    ("V2_SESSION_GET", "v2.session.get"),
    ("V2_SESSION_CREATE", "v2.session.create"),
    ("V2_SESSION_PROMPT", "v2.session.prompt"),
    ("V2_SESSION_WAIT", "v2.session.wait"),
    ("V2_SESSION_INTERRUPT", "v2.session.interrupt"),
    ("V2_SESSION_EVENTS", "v2.session.events"),
    ("V2_EVENT_SUBSCRIBE", "v2.event.subscribe"),
    ("V2_MODEL_LIST", "v2.model.list"),
    ("V2_PROVIDER_LIST", "v2.provider.list"),
    ("V2_PROVIDER_GET", "v2.provider.get"),
    ("V2_FS_READ", "v2.fs.read"),
    ("V2_FS_LIST", "v2.fs.list"),
    ("V2_FS_FIND", "v2.fs.find"),
    ("V2_PERMISSION_REQUEST_LIST", "v2.permission.request.list"),
    ("V2_PERMISSION_SAVED_LIST", "v2.permission.saved.list"),
    ("V2_PERMISSION_SAVED_REMOVE", "v2.permission.saved.remove"),
    ("V2_QUESTION_REQUEST_LIST", "v2.question.request.list"),
    ("V2_SESSION_ACTIVE", "v2.session.active"),
    ("V2_SESSION_SWITCH_AGENT", "v2.session.switchAgent"),
    ("V2_SESSION_SWITCH_MODEL", "v2.session.switchModel"),
    ("V2_SESSION_COMPACT", "v2.session.compact"),
    ("V2_SESSION_CONTEXT", "v2.session.context"),
    ("V2_SESSION_HISTORY", "v2.session.history"),
    ("V2_SESSION_MESSAGE", "v2.session.message"),
    ("V2_SESSION_MESSAGES", "v2.session.messages"),
    ("V2_SESSION_REVERT_STAGE", "v2.session.revert.stage"),
    ("V2_SESSION_REVERT_CLEAR", "v2.session.revert.clear"),
    ("V2_SESSION_REVERT_COMMIT", "v2.session.revert.commit"),
    ("V2_SESSION_PERMISSION_LIST", "v2.session.permission.list"),
    ("V2_SESSION_PERMISSION_CREATE", "v2.session.permission.create"),
    ("V2_SESSION_PERMISSION_GET", "v2.session.permission.get"),
    ("V2_SESSION_PERMISSION_REPLY", "v2.session.permission.reply"),
    ("V2_SESSION_QUESTION_LIST", "v2.session.question.list"),
    ("V2_SESSION_QUESTION_REPLY", "v2.session.question.reply"),
    ("V2_SESSION_QUESTION_REJECT", "v2.session.question.reject"),
    ("V2_HEALTH_GET", "v2.health.get"),
    ("V2_LOCATION_GET", "v2.location.get"),
    ("V2_AGENT_LIST", "v2.agent.list"),
    ("V2_COMMAND_LIST", "v2.command.list"),
    ("V2_SKILL_LIST", "v2.skill.list"),
    ("V2_REFERENCE_LIST", "v2.reference.list"),
    ("V2_INTEGRATION_LIST", "v2.integration.list"),
    ("V2_INTEGRATION_GET", "v2.integration.get"),
    ("V2_INTEGRATION_CONNECT_KEY", "v2.integration.connect.key"),
    ("V2_INTEGRATION_CONNECT_OAUTH", "v2.integration.connect.oauth"),
    ("V2_INTEGRATION_ATTEMPT_STATUS", "v2.integration.attempt.status"),
    ("V2_INTEGRATION_ATTEMPT_CANCEL", "v2.integration.attempt.cancel"),
    ("V2_INTEGRATION_ATTEMPT_COMPLETE", "v2.integration.attempt.complete"),
    ("V2_CREDENTIAL_UPDATE", "v2.credential.update"),
    ("V2_CREDENTIAL_REMOVE", "v2.credential.remove"),
]


def operation_index(spec: dict) -> dict[str, tuple[str, str]]:
    found: dict[str, tuple[str, str]] = {}
    for path, path_item in spec.get("paths", {}).items():
        for method, operation in path_item.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete", "head", "options"}:
                continue
            if not isinstance(operation, dict):
                continue
            operation_id = operation.get("operationId")
            if operation_id:
                found[operation_id] = (method.upper(), path)
    return found


def render(spec: dict, upstream: dict) -> str:
    index = operation_index(spec)
    missing = [operation_id for _, operation_id in OPERATIONS if operation_id not in index]
    if missing:
        raise SystemExit(f"pinned OpenAPI contract is missing required operations: {', '.join(missing)}")

    lines = [
        "// @generated by scripts/generate_contract.py. Do not edit by hand.",
        f'pub const CONTRACT_UPSTREAM_SHA: &str = "{upstream["upstream_commit"]}";',
        "",
    ]
    for rust_name, operation_id in OPERATIONS:
        method, path = index[operation_id]
        lines.extend(
            [
                f'pub const {rust_name}_METHOD: &str = "{method}";',
                f'pub const {rust_name}_PATH: &str = "{path}";',
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not SPEC.exists():
        if args.check:
            print("spec/openapi.json is not checked in yet; contract refresh workflow will create it")
            return
        raise SystemExit("spec/openapi.json does not exist; run scripts/update-openapi first")

    spec = json.loads(SPEC.read_text())
    upstream = json.loads(UPSTREAM.read_text())
    output = render(spec, upstream)

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != output:
            raise SystemExit("generated contract manifest is stale; run scripts/generate_contract.py")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output)


if __name__ == "__main__":
    main()
